name: catalogbuilder 
channels:
  - conda-forge 
  - noaa-gfdl
  - defaults
dependencies:
  - python
  - pytest
  - setuptools
  - click
  - xarray
  - pandas
  - jsondiff
  - intake-esm=2023.7.7
  - boto3
