name: catalogbuilder 
channels:
  - conda-forge 
  - noaa-gfdl
  - defaults
dependencies:
  - python>=3.11
  - pytest
  - setuptools
  - click
  - xarray>=2025.01.1
  - zarr>=3
  - pandas
  - jsondiff
  - intake-esm
  - boto3
  - importlib_resources
