package:
  name: catalogbuilder
  version: 2026.02.01

source:
  path: .
# thank you bennet- the git url messes with conda build, which 
# automatically checks out the default branch when given a URL

build:
      script: "{{ PYTHON }} -m pip install . -vv"
      number: 0
      noarch: python
requirements:
  host: 
    - python >=3.11
    - pip
    - setuptools 
  run:
    - python >=3.11
    - pytest
    - click
    - xarray >=2025.01.1
    - zarr >=3
    - pandas
    - jsondiff
    - conda-forge::intake-esm
    - boto3
test:
  imports:
    - catalogbuilder
    - catalogbuilder.cats
    - catalogbuilder.scripts
    - catalogbuilder.scripts.gen_intake_gfdl
about:
  home:
