package:
  name: catalogbuilder
  version: 2.0.1

source:
  git_url: https://github.com/NOAA-GFDL/CatalogBuilder.git
  git_branch: main
  path: .

build:
      script: "{{ PYTHON }} -m pip install . -vv"
      number: 0
      noarch: python
requirements:
  host: 
    - python
    - pip 
  run:
    - python
    - pytest
    - click
    - xarray
    - pandas
    - jsondiff
    - conda-forge::intake-esm=2023.7.7
    - boto3
test:
  imports:
    - catalogbuilder
    - catalogbuilder.scripts
    - catalogbuilder.cats
about:
  home:
