package:
  name: catalogbuilder
  version: 2.0.2

source:
  path: .
# thank you bennet- the git url messes with conda build, which 
# automatically checks out the default branch when given a URL

build:
      script: "{{ PYTHON }} -m pip install . -vv"
      number: 0
      noarch: python
requirements:
  host: 
    - python
    - pip 
  run:
    - python
    - pytest
    - click
    - xarray
    - pandas
    - jsondiff
    - conda-forge::intake-esm
    - boto3
test:
  imports:
    - catalogbuilder
    - catalogbuilder.cats
    - catalogbuilder.scripts
    - catalogbuilder.scripts.gen_intake_gfdl
about:
  home:
